
# IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [2]:
data = pd.read_table("10223261.txt", delim_whitespace=True)
data

fire  year  temp  humidity  rainfall  drought_code  buildup_index  day  \
0     no  2015    28        59       0.0          8.06           3.47    1   
1     no  2010    30        61       1.3          8.17           4.03    2   
2     no  2009    26        83      13.1          8.08           3.59    3   
3     no  2017    25        87       2.5          7.18           2.42    4   
4     no  2014    28        77       0.0         14.98           4.63    5   
..   ...   ...   ...       ...       ...           ...            ...  ...   
199  yes  2017    31        67       0.0         45.15          17.89   26   
200   no  2017    29        89       4.4          8.74           6.52   27   
201   no  2009    27        88       0.5          8.87           3.71   28   
202   no  2016    25        56       0.1         15.54           6.10   29   
203   no  2012    24        62       0.2         16.72           5.75   30   

     month  wind_speed  
0        6          19  
1        6          13  
2        6          22  
3        6          15  
4        6          18  
..     ...         ...  
199      9          15  
200      9          15  
201      9          30  
202      9          20  
203      9          17  

[204 rows x 10 columns]

In [3]:
data.head()

fire  year  temp  humidity  rainfall  drought_code  buildup_index  day  \
0   no  2015    28        59       0.0          8.06           3.47    1   
1   no  2010    30        61       1.3          8.17           4.03    2   
2   no  2009    26        83      13.1          8.08           3.59    3   
3   no  2017    25        87       2.5          7.18           2.42    4   
4   no  2014    28        77       0.0         14.98           4.63    5   

   month  wind_speed  
0      6          19  
1      6          13  
2      6          22  
3      6          15  
4      6          18

In [4]:
data.keys()

Index(['fire', 'year', 'temp', 'humidity', 'rainfall', 'drought_code',
       'buildup_index', 'day', 'month', 'wind_speed'],
      dtype='object')

In [5]:
data['fire'] = data['fire'].map({'yes':1, 'no':0})
data['fire']

0      0
1      0
2      0
3      0
4      0
      ..
199    1
200    0
201    0
202    0
203    0
Name: fire, Length: 204, dtype: int64

# DATA SPLITTING INTO TRAINING AND TESTING

In [6]:
features = ['year', 'temp', 'humidity', 'rainfall', 'drought_code', 'buildup_index', 'day', 'month', 'wind_speed']
x = data.loc[:, features]
y = data.loc[:, ['fire']]

In [7]:
data['fire'].value_counts()

1    107
0     97
Name: fire, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=70, train_size = 0.67)

In [9]:
x_train.shape

(136, 9)

In [10]:
x_test.shape

(68, 9)

In [11]:
y_train.shape

(136, 1)

In [12]:
y_test.shape

(68, 1)

In [13]:
x_train_array = np.array(x_train)
y_train_array = np.array(y_train)
x_test_array = np.array(x_test)
y_test_array = np.array(y_test)
x_train_array.shape

(136, 9)

# INITIALIZING RANDOM WEIGHTS AND BIAS

In [164]:
w1 = np.zeros((1,9))
b1 = 0
w2 = np.zeros((1,9))
b2 = 0
hidden = [1,9]
h1 = np.matrix(hidden)
w2.shape

(1, 9)

In [165]:
w1.shape

(1, 9)

In [166]:
y_train_array.shape

(136, 1)

# FORWARD PROPAGATION

In [176]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def der_sigmoid(x):
    return sigmoid(x) * 1 - sigmoid(x)

def forward(x, w1, b1, w2, b2):
    h1 = np.dot(np.matrix.transpose(w1),np.matrix.transpose(x)) + b1    # 1st layer input to 1st hidden layer
    h1o = sigmoid(h1)
    print(h1o.shape)# 1st hidden layer apply sigmoid function
    
    y = np.dot(w2,h1o) + b2    # 1st hidden layer output to second hidden layer
    yo = sigmoid(y)
    print(yo.shape)# 2nd hidden layer apply sigmoid activation function
    
    return h1o, yo


In [178]:
yout = forward(y_train_array, w1, b1, w2, b2)
yout_array = np.array(yout)
yout_array.shape

# yout_array = np.matrix.reshape(yout_ar, [2,1])

# yout_array.shape

(9, 136)
(1, 136)


C:\Users\anagh\AppData\Local\Temp\ipykernel_14176\1561900663.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  yout_array = np.array(yout)


(2,)

# BACK PROPAGATION GRADIENT DESCENT

In [145]:
def mse(y_true,y_pred):
    return 0.5*((y_pred-y_true)**2).mean()


error = mse(yout_array,np.matrix.transpose(y_train_array))
print(error.shape)
print(error)

def accuracy(y_true, y_pred):
    return 1 - (error/len(yout_array))

acc = accuracy(yout, y_train_array)
print(acc)
print(acc.shape)


(9, 136)
[[0.125 0.125 0.125 ... 0.125 0.125 0.125]
 [0.125 0.125 0.125 ... 0.125 0.125 0.125]
 [0.125 0.125 0.125 ... 0.125 0.125 0.125]
 ...
 [0.125 0.125 0.125 ... 0.125 0.125 0.125]
 [0.125 0.125 0.125 ... 0.125 0.125 0.125]
 [0.125 0.125 0.125 ... 0.125 0.125 0.125]]
[[0.9375 0.9375 0.9375 ... 0.9375 0.9375 0.9375]
 [0.9375 0.9375 0.9375 ... 0.9375 0.9375 0.9375]
 [0.9375 0.9375 0.9375 ... 0.9375 0.9375 0.9375]
 ...
 [0.9375 0.9375 0.9375 ... 0.9375 0.9375 0.9375]
 [0.9375 0.9375 0.9375 ... 0.9375 0.9375 0.9375]
 [0.9375 0.9375 0.9375 ... 0.9375 0.9375 0.9375]]
(9, 136)


In [146]:
def wnew(weights, learning_rate, error):
    wu = weights - learning_rate*der_sigmoid(error)
    return wu

def bnew(bias, learning_rate, error):
    bu = -learning_rate * der_sigmoid(error)
    return bu

w2_new = wnew(w2, 0.1, error)
b2_new = bnew(b2, 0.1, error)

w1_new = wnew(w1, 0.001, error)
b1_new = bnew(b1, 0.01, error)

print(w2_new.shape)
print(b2_new.shape)
print(w1_new.shape)
print(b1_new.shape)

(9, 136)
(9, 136)
(9, 136)
(9, 136)


In [149]:
def backward(yout_array, w1_new, b1_new, w2_new, b2_new):
    
    h1_new = np.dot(w2_new,yout_array) + b2_new    # 1st layer input to 1st hidden layer
    h1o_new = sigmoid(h1_new)      # 1st hidden layer apply sigmoid function
    
    x = np.dot(w1,h1_new) + b1_new    # 1st hidden layer output to second hidden layer
    xo = sigmoid(x)      # 2nd hidden layer apply sigmoid activation function
    

    return h1o_new, xo


In [150]:
xout = backward(yout_array, w1_new, b1_new, w2_new, b2_new)
xout

ValueError: shapes (9,136) and (2,1) not aligned: 136 (dim 1) != 2 (dim 0)

In [151]:
def last_forward(xout, w1_new, b1_new, w2_new, b2_new):
    xout_array = np.array(xout)
    
    h1_next = np.dot(xout_array,w1_new) + b1_new    # 1st layer input to 1st hidden layer
    h1o_next = sigmoid(h1_next)      # 1st hidden layer apply sigmoid function
    
    y_next = np.dot(h1o_next,w2_new) + b2_new    # 1st hidden layer output to second hidden layer
    yo_next = sigmoid(y_next)      # 2nd hidden layer apply sigmoid activation function
    
    return h1o_next, yo_next

In [160]:
def mlp(x, w1, b1, w2, b2):
    for i in range(1, 10000):
        forward(x_train_array, w1, b1, w2, b2)
        backward(yout, w1_new, b1_new, w2_new, b2_new)
        last_forward(xout, w1_new, b1_new, w2_new, b2_new)
        break

In [161]:
# def predict(x, y, learning):

#     probas, caches = L_model_forward(X, parameters)

#     for i in range(0, probas.shape[1]):
#         if probas[0, i] > 0.5:
#             p[0, i] = 1
#         else:
#             p[0, i] = 0
#     print("Accuracy: " + str(np.sum((p == y)/m)))

#     return p
  


In [162]:
mlp(y_train_array, w1, b1, w2, b2)

(9, 9)
(9, 136)


ValueError: shapes (9,136) and (2,) not aligned: 136 (dim 1) != 2 (dim 0)